# Generated by Django 5.1.6 on 2026-07-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adhoctask_adhoctaskattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoctask',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
