# Generated by Django 5.2.8 on 2026-07-13 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_adhoctask_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adhoctask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_adhoc_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adhoctask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhoc_tasks_legacy', to=settings.AUTH_USER_MODEL),
        ),
    ]
