# Generated by Django 5.2.8 on 2026-07-13 06:33

from django.db import migrations


def copy_assignees(apps, schema_editor):
    AdHocTask = apps.get_model("core", "AdHocTask")
    for task in AdHocTask.objects.all():
        if task.assigned_to_id:
            task.assignees.add(task.assigned_to_id)

def reverse_copy_assignees(apps, schema_editor):
    # Reverse operation if we downgrade (assignees back to assigned_to is lossy, but we pick the first one)
    AdHocTask = apps.get_model("core", "AdHocTask")
    for task in AdHocTask.objects.all():
        first_assignee = task.assignees.first()
        if first_assignee:
            task.assigned_to = first_assignee
            task.save(update_fields=["assigned_to"])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adhoctask_assignees_alter_adhoctask_assigned_to'),
    ]

    operations = [
        migrations.RunPython(copy_assignees, reverse_copy_assignees),
    ]
