# Generated by Django 5.2.8 on 2026-07-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_copy_adhoctask_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhoctask',
            name='assigned_to',
        ),
    ]
