# Generated by Django 5.1.1 on 2026-08-27 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_projectarchitecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_leaders',
            field=models.ManyToManyField(blank=True, related_name='led_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
