# Generated by Django 5.1.6 on 2026-10-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_task_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='JMS Tech', max_length=200)),
                ('company_tagline', models.CharField(blank=True, default='Project Management & Delivery Tracking', max_length=300)),
                ('logo_url', models.URLField(blank=True, default='', help_text='URL to the company logo shown in PDF/email headers.')),
                ('pdf_accent_color', models.CharField(default='#2563eb', help_text='Hex color for PDF accent elements (e.g. #2563eb)', max_length=7)),
                ('pdf_header_text', models.TextField(blank=True, default='', help_text='Additional text shown in PDF headers (e.g. address, website).')),
                ('pdf_footer_text', models.TextField(blank=True, default='Generated by JMS Delivery Hub', help_text='Text shown in PDF/email footers.')),
                ('email_signature', models.TextField(blank=True, default='— JMS Delivery Hub', help_text='Signature appended to plain-text emails.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
            },
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='next_meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_format', models.TextField(blank=True, default='', help_text='Format template for weekly report. Leave blank to use auto-generated text.')),
                ('daily_format', models.TextField(blank=True, default='', help_text='Format template for daily report. Leave blank to use auto-generated text.')),
                ('custom_format', models.TextField(blank=True, default='', help_text='Format template for custom/date-range report. Leave blank to use auto-generated text.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_template', to='core.project')),
            ],
        ),
    ]
