# Generated by Django 5.1.1 on 2026-10-05 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_organizationsettings_meetingminutes_meeting_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Exact deliverable / scope remaining', max_length=300)),
                ('status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('DELAYED', 'Delayed'), ('COMPLETED', 'Completed')], default='ON_TRACK', max_length=15)),
                ('work_completed', models.TextField(blank=True, help_text='Work completed to date')),
                ('stakeholder_dependency', models.TextField(blank=True, help_text='Stakeholder / dependency, if any')),
                ('next_milestone_desc', models.CharField(blank=True, help_text='Next milestone description', max_length=300)),
                ('committed_date', models.DateField(blank=True, help_text='Next milestone committed date', null=True)),
                ('final_completion_date', models.DateField(blank=True, help_text='Final completion / go-live date', null=True)),
                ('blocker', models.TextField(blank=True, help_text='Blocker if at risk')),
                ('recovery_action', models.TextField(blank=True, help_text='Recovery action if at risk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_milestones', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project')),
            ],
            options={
                'ordering': ['final_completion_date', 'created_at'],
            },
        ),
    ]
