# Generated by Django 5.1.6 on 2026-10-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_projectmilestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='owner',
            field=models.CharField(blank=True, help_text='Owner name (client-side contact or responsible party)', max_length=200, null=True),
        ),
    ]
