# Generated by Django 5.1.1 on 2026-10-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_projectmilestone_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('JMS', 'JMS Projects'), ('NAAVYA', 'Naavya AI'), ('DEMO', 'Demo')], default='JMS', help_text='Hub section: JMS Projects, Naavya AI, or Demo', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('SOFTWARE', 'Custom Software'), ('SERVICES', 'Services'), ('VOICE', 'Voice Only'), ('VOICE_WHATSAPP', 'Voice + WhatsApp'), ('WHATSAPP', 'WhatsApp Only'), ('DEMO', 'Demo')], default='SOFTWARE', help_text='Specific project type within the category', max_length=20),
        ),
    ]
