# Generated by Django 5.1.1 on 2026-10-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_project_category_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
